<?php

$categorias = [
    'bruto' => 'Bruto',
    'ferramentas' => 'Ferramentas',
    'acabamento' => 'Acabamento',
];

$produtos_base = [
    [
        'id' => 1,
        'nome' => 'Martelo',
        'marca' => 'Portland',
        'quantidade_minima' => 30,
        'quantidade_atual' => 50,
        'preco_unitario' => 25.00,
        'preco_total' => 750.00,
        'imagem' => '1.png',
        'categoria' => 'bruto'
    ],
    [
        'id' => 2,
        'nome' => 'Cimento',
        'marca' => 'Portland',
        'quantidade_minima' => 50,
        'quantidade_atual' => 30,
        'preco_unitario' => 25.00,
        'preco_total' => 750.00,
        'imagem' => '2.png',
        'categoria' => 'ferramentas'
    ],
    [
        'id' => 3,
        'nome' => 'Tijolo',
        'marca' => 'Cerâmica',
        'quantidade_minima' => 200,
        'quantidade_atual' => 180,
        'preco_unitario' => 1.00,
        'preco_total' => 180.00,
        'imagem' => '3.png',
        'categoria' => 'acabamento'
    ]
];


$fornecedores_base = [
    [
        'id_2' => 1,
        'fornecedor' => 'Votorantim',
        'especialidade' => 'Base e Estrutura',
        'marca_principal' => 'Cimento Itaú, Votomassa',
        'troca_devolucao' => 'Só sacos rasgados no ato',
        'prazo_entrega' => '24h a 48h',
        'nome_consultor' => 'Marcos Souza',
        'contato' => '(11) 98888-7777',
        'email' => 'pedidos@votorantim.com.br',
        'cnpj' => '01.234.567/0001-89',
        'pagamento_condicacao' => 'Boleto 28 dias',
        'pedido_min' => 'R$ 2.000,00',
        'confiabilidade' => 'Alta - Líder de mercado',
    ],

    [
        'id_2' => 2,
        'fornecedor' => 'Amanco Wavin',
        'especialidade' => 'Hidráulica e Esgoto',
        'marca_principal' => 'Amanco, QuickCheck',
        'troca_devolucao' => '30 dias p/ defeito fábrica',
        'prazo_entrega' => 'Toda Terça e Quinta',
        'nome_consultor' => 'Cláudia Lira',
        'contato' => '(11) 97777-6666',
        'email' => 'vendas@amanco.com.br',
        'cnpj' => '12.345.678/0001-00',
        'pagamento_condicacao' => 'Boleto 14/28/42 dias',
        'pedido_min' => 'R$ 1.500,00',
        'confiabilidade' => 'Excelente prazo',
    ],

    [
        'id_2' => 3,
        'fornecedor' => 'Gerdau',
        'especialidade' => 'Ferragens e Aço',
        'marca_principal' => 'Vergalhões, Pregos',
        'troca_devolucao' => 'Não aceita devolução',
        'prazo_entrega' => '3 dias úteis',
        'nome_consultor' => 'Ricardo Ferro',
        'contato' => '(11) 96666-5555',
        'email' => 'aco@gerdau.com.br',
        'cnpj' => '23.456.789/0001-11',
        'pagamento_condicacao' => 'Antecipado / Crédito',
        'pedido_min' => '500kg',
        'confiabilidade' => 'Material certificado',
    ],
    [
        'id_2' => 4,
        'fornecedor' => 'Suvinil',
        'especialidade' => 'Tintas e Pintura',
        'marca_principal' => 'Suvinil, Glasu!',
        'troca_devolucao' => 'Troca de latas amassadas',
        'prazo_entrega' => '5 dias úteis',
        'nome_consultor' => 'Beatriz Tintas',
        'contato' => '(11) 95555-4444',
        'email' => 'comercial@suvinil.com.br',
        'cnpj' => '34.567.890/0001-22',
        'pagamento_condicacao' => 'Boleto 30/60 dias',
        'pedido_min' => 'R$ 3.000,00',
        'confiabilidade' => 'Melhor mix de cores',
    ],
    [
        'id_2' => 5,
        'fornecedor' => 'Lorenzetti',
        'especialidade' => 'Elétrica e Metais',
        'marca_principal' => 'Chuveiros, Torneiras',
        'troca_devolucao' => 'Assistência Técnica Direta',
        'prazo_entrega' => '2 dias úteis',
        'nome_consultor' => 'André Metais',
        'contato' => '(11) 94444-3333',
        'email' => 'assistencia@lorenzetti.com.br',
        'cnpj' => '45.678.901/0001-33',
        'pagamento_condicacao' => 'Depósito / Boleto',
        'pedido_min' => 'R$ 800,00',
        'confiabilidade' => 'Ótimo pós-venda',
    ],
    [
        'id_2' => 6,
        'fornecedor' => 'Vedacit',
        'especialidade' => 'Impermeabilização',
        'marca_principal' => 'Vedapren, Neutrol, Vedacit',
        'troca_devolucao' => 'Somente embalagens lacradas',
        'prazo_entrega' => '3 a 4 dias úteis',
        'nome_consultor' => 'Sergio Imper',
        'contato' => '(11) 93333-2222',
        'email' => 'vendas@vedacit.com.br',
        'cnpj' => '56.789.012/0001-44',
        'pagamento_condicacao' => 'Boleto 21 dias',
        'pedido_min' => 'R$ 1.200,00',
        'confiabilidade' => 'Referência técnica',
    ],

    [
        'id_2' => 7,
        'fornecedor' => 'Pisos Porto Ferreira',
        'especialidade' => 'Revestimentos',
        'marca_principal' => 'Cerâmicas, Pisos Externos',
        'troca_devolucao' => 'Quebras acima de 3% da carga',
        'prazo_entrega' => '7 a 10 dias úteis',
        'nome_consultor' => 'Elaine Pisos',
        'contato' => '(19) 92222-1111',
        'email' => 'porto@ferreira.com.br',
        'cnpj' => '67.890.123/0001-55',
        'pagamento_condicacao' => '50% sinal + 50% entrega',
        'pedido_min' => '50 m²',
        'confiabilidade' => 'Qualidade Premium',
    ],

    [
        'id_2' => 8,
        'fornecedor' => 'Bosch Ferramentas',
        'especialidade' => 'Ferramentas Elétricas',
        'marca_principal' => 'Bosch, Skil, Dremel',
        'troca_devolucao' => 'Garantia via Assistência',
        'prazo_entrega' => '48h (Capital)',
        'nome_consultor' => 'Fabio Ferramentas',
        'contato' => '(11) 91111-0000',
        'email' => '78.901.234/0001-66',
        'cnpj' => '78.901.234/0001-66',
        'pagamento_condicacao' => 'Cartão BNDES / Boleto',
        'pedido_min' => 'R$ 2.500,00',
        'confiabilidade' => 'Alta durabilidade',
    ],

];

?>