<?php

$categorias = [
    'bruto' => 'Bruto',
    'ferramentas' => 'Ferramentas',
    'acabamento' => 'Acabamento',
];

$categorias_fornecedores = [
    'base_estrutura' => 'Base e Estrutura',
    'hidraulica_esgoto' => 'Hidráulica e Esgoto',
    'revestimentos' => 'Revestimentos',
];

$produtos_base = [

    // ================= BRUTO (1-10) =================
    [
        'id' => 1,
        'nome' => 'Areia Média',
        'marca' => 'Local',
        'quantidade_minima' => 50,
        'quantidade_atual' => 80,
        'preco_unitario' => 120.00,
        'preco_total' => 9600.00,
        'imagem' => '1.png',
        'categoria' => 'bruto'
    ],
    [
        'id' => 2,
        'nome' => 'Brita 1',
        'marca' => 'Pedreira SP',
        'quantidade_minima' => 40,
        'quantidade_atual' => 60,
        'preco_unitario' => 150.00,
        'preco_total' => 9000.00,
        'imagem' => '2.png',
        'categoria' => 'bruto'
    ],
    [
        'id' => 3,
        'nome' => 'Cimento CP II',
        'marca' => 'Votorantim',
        'quantidade_minima' => 100,
        'quantidade_atual' => 90,
        'preco_unitario' => 30.00,
        'preco_total' => 2700.00,
        'imagem' => '3.png',
        'categoria' => 'bruto'
    ],
    [
        'id' => 4,
        'nome' => 'Tijolo Baiano',
        'marca' => 'Cerâmica Forte',
        'quantidade_minima' => 500,
        'quantidade_atual' => 450,
        'preco_unitario' => 0.90,
        'preco_total' => 405.00,
        'imagem' => '4.png',
        'categoria' => 'bruto'
    ],
    [
        'id' => 5,
        'nome' => 'Bloco de Concreto',
        'marca' => 'Blocos SP',
        'quantidade_minima' => 300,
        'quantidade_atual' => 350,
        'preco_unitario' => 2.50,
        'preco_total' => 875.00,
        'imagem' => '5.png',
        'categoria' => 'bruto'
    ],
    [
        'id' => 6,
        'nome' => 'Cal Hidratada',
        'marca' => 'Itaú',
        'quantidade_minima' => 60,
        'quantidade_atual' => 70,
        'preco_unitario' => 18.00,
        'preco_total' => 1260.00,
        'imagem' => '6.png',
        'categoria' => 'bruto'
    ],
    [
        'id' => 7,
        'nome' => 'Vergalhão 10mm',
        'marca' => 'Gerdau',
        'quantidade_minima' => 80,
        'quantidade_atual' => 100,
        'preco_unitario' => 45.00,
        'preco_total' => 4500.00,
        'imagem' => '7.png',
        'categoria' => 'bruto'
    ],
    [
        'id' => 8,
        'nome' => 'Vergalhão 8mm',
        'marca' => 'Gerdau',
        'quantidade_minima' => 70,
        'quantidade_atual' => 60,
        'preco_unitario' => 35.00,
        'preco_total' => 2100.00,
        'imagem' => '8.png',
        'categoria' => 'bruto'
    ],
    [
        'id' => 9,
        'nome' => 'Argamassa AC1',
        'marca' => 'Quartzolit',
        'quantidade_minima' => 50,
        'quantidade_atual' => 65,
        'preco_unitario' => 28.00,
        'preco_total' => 1820.00,
        'imagem' => '9.png',
        'categoria' => 'bruto'
    ],
    [
        'id' => 10,
        'nome' => 'Concreto Ensacado',
        'marca' => 'Votorantim',
        'quantidade_minima' => 40,
        'quantidade_atual' => 55,
        'preco_unitario' => 32.00,
        'preco_total' => 1760.00,
        'imagem' => '10.png',
        'categoria' => 'bruto'
    ],

    // ================= FERRAMENTAS (11-20) =================
    [
        'id' => 11,
        'nome' => 'Martelo',
        'marca' => 'Tramontina',
        'quantidade_minima' => 20,
        'quantidade_atual' => 30,
        'preco_unitario' => 40.00,
        'preco_total' => 1200.00,
        'imagem' => '11.png',
        'categoria' => 'ferramentas'
    ],
    [
        'id' => 12,
        'nome' => 'Chave de Fenda',
        'marca' => 'Bosch',
        'quantidade_minima' => 25,
        'quantidade_atual' => 35,
        'preco_unitario' => 15.00,
        'preco_total' => 525.00,
        'imagem' => '12.png',
        'categoria' => 'ferramentas'
    ],
    [
        'id' => 13,
        'nome' => 'Furadeira',
        'marca' => 'Makita',
        'quantidade_minima' => 15,
        'quantidade_atual' => 12,
        'preco_unitario' => 250.00,
        'preco_total' => 3000.00,
        'imagem' => '13.png',
        'categoria' => 'ferramentas'
    ],
    [
        'id' => 14,
        'nome' => 'Serrote',
        'marca' => 'Tramontina',
        'quantidade_minima' => 15,
        'quantidade_atual' => 12,
        'preco_unitario' => 35.00,
        'preco_total' => 700.00,
        'imagem' => '14.png',
        'categoria' => 'ferramentas'
    ],
    [
        'id' => 15,
        'nome' => 'Alicate',
        'marca' => 'Vonder',
        'quantidade_minima' => 50,
        'quantidade_atual' => 32,
        'preco_unitario' => 28.00,
        'preco_total' => 700.00,
        'imagem' => '15.png',
        'categoria' => 'ferramentas'
    ],
    [
        'id' => 16,
        'nome' => 'Trena 5m',
        'marca' => 'Stanley',
        'quantidade_minima' => 15,
        'quantidade_atual' => 18,
        'preco_unitario' => 22.00,
        'preco_total' => 396.00,
        'imagem' => '16.png',
        'categoria' => 'ferramentas'
    ],
    [
        'id' => 17,
        'nome' => 'Nível',
        'marca' => 'Bosch',
        'quantidade_minima' => 10,
        'quantidade_atual' => 15,
        'preco_unitario' => 55.00,
        'preco_total' => 825.00,
        'imagem' => '17.png',
        'categoria' => 'ferramentas'
    ],
    [
        'id' => 18,
        'nome' => 'Parafusadeira',
        'marca' => 'Makita',
        'quantidade_minima' => 8,
        'quantidade_atual' => 10,
        'preco_unitario' => 300.00,
        'preco_total' => 3000.00,
        'imagem' => '18.png',
        'categoria' => 'ferramentas'
    ],
    [
        'id' => 19,
        'nome' => 'Espátula',
        'marca' => 'Atlas',
        'quantidade_minima' => 30,
        'quantidade_atual' => 40,
        'preco_unitario' => 12.00,
        'preco_total' => 480.00,
        'imagem' => '19.png',
        'categoria' => 'ferramentas'
    ],
    [
        'id' => 20,
        'nome' => 'Desempenadeira',
        'marca' => 'Vonder',
        'quantidade_minima' => 25,
        'quantidade_atual' => 22,
        'preco_unitario' => 18.00,
        'preco_total' => 540.00,
        'imagem' => '20.png',
        'categoria' => 'ferramentas'
    ],

    // ================= ACABAMENTO (21-30) =================
    [
        'id' => 21,
        'nome' => 'Piso Cerâmico',
        'marca' => 'Portobello',
        'quantidade_minima' => 100,
        'quantidade_atual' => 120,
        'preco_unitario' => 35.00,
        'preco_total' => 4200.00,
        'imagem' => '21.png',
        'categoria' => 'acabamento'
    ],
    [
        'id' => 22,
        'nome' => 'Azulejo',
        'marca' => 'Eliane',
        'quantidade_minima' => 80,
        'quantidade_atual' => 90,
        'preco_unitario' => 28.00,
        'preco_total' => 2520.00,
        'imagem' => '22.png',
        'categoria' => 'acabamento'
    ],
    [
        'id' => 23,
        'nome' => 'Tinta Acrílica',
        'marca' => 'Suvinil',
        'quantidade_minima' => 40,
        'quantidade_atual' => 50,
        'preco_unitario' => 120.00,
        'preco_total' => 6000.00,
        'imagem' => '23.png',
        'categoria' => 'acabamento'
    ],
    [
        'id' => 24,
        'nome' => 'Massa Corrida',
        'marca' => 'Coral',
        'quantidade_minima' => 30,
        'quantidade_atual' => 45,
        'preco_unitario' => 60.00,
        'preco_total' => 2700.00,
        'imagem' => '24.png',
        'categoria' => 'acabamento'
    ],
    [
        'id' => 25,
        'nome' => 'Rejunte',
        'marca' => 'Quartzolit',
        'quantidade_minima' => 50,
        'quantidade_atual' => 65,
        'preco_unitario' => 15.00,
        'preco_total' => 975.00,
        'imagem' => '25.png',
        'categoria' => 'acabamento'
    ],
    [
        'id' => 26,
        'nome' => 'Rodapé',
        'marca' => 'Duratex',
        'quantidade_minima' => 60,
        'quantidade_atual' => 53,
        'preco_unitario' => 20.00,
        'preco_total' => 1400.00,
        'imagem' => '26.png',
        'categoria' => 'acabamento'
    ],
    [
        'id' => 27,
        'nome' => 'Porta de Madeira',
        'marca' => 'Pormade',
        'quantidade_minima' => 10,
        'quantidade_atual' => 8,
        'preco_unitario' => 350.00,
        'preco_total' => 4200.00,
        'imagem' => '27.png',
        'categoria' => 'acabamento'
    ],
    [
        'id' => 28,
        'nome' => 'Janela Alumínio',
        'marca' => 'Sasazaki',
        'quantidade_minima' => 8,
        'quantidade_atual' => 10,
        'preco_unitario' => 450.00,
        'preco_total' => 4500.00,
        'imagem' => '28.png',
        'categoria' => 'acabamento'
    ],
    [
        'id' => 29,
        'nome' => 'Verniz',
        'marca' => 'Sparlack',
        'quantidade_minima' => 20,
        'quantidade_atual' => 25,
        'preco_unitario' => 55.00,
        'preco_total' => 1375.00,
        'imagem' => '29.png',
        'categoria' => 'acabamento'
    ],
    [
        'id' => 30,
        'nome' => 'Selador',
        'marca' => 'Coral',
        'quantidade_minima' => 40,
        'quantidade_atual' => 30,
        'preco_unitario' => 70.00,
        'preco_total' => 2100.00,
        'imagem' => '30.png',
        'categoria' => 'acabamento'
    ],

];


$fornecedores_base = [

    // ================= BASE E ESTRUTURA (1-8) =================
    [
        'id_2' => 1,
        'fornecedor' => 'Votorantim',
        'especialidade' => 'base_estrutura',
        'marca_principal' => 'Cimento Itaú, Votomassa',
        'troca_devolucao' => 'Só sacos rasgados no ato',
        'prazo_entrega' => '24h a 48h',
        'nome_consultor' => 'Marcos Souza',
        'contato' => '(11) 98888-7777',
        'email' => 'pedidos@votorantim.com.br',
        'cnpj' => '01.234.567/0001-89',
        'pagamento_condicacao' => 'Boleto 28 dias',
        'pedido_min' => 'R$ 2.000,00',
        'confiabilidade' => 'Alta - Líder de mercado',
    ],
    [
        'id_2' => 2,
        'fornecedor' => 'Lafarge',
        'especialidade' => 'base_estrutura',
        'marca_principal' => 'Cimento Lafarge, Areia, Brita',
        'troca_devolucao' => 'Até 30 dias',
        'prazo_entrega' => '24h a 72h',
        'nome_consultor' => 'Carlos Mendes',
        'contato' => '(11) 99999-8888',
        'email' => 'vendas@lafarge.com.br',
        'cnpj' => '02.345.678/0001-90',
        'pagamento_condicacao' => 'Boleto 21 dias',
        'pedido_min' => 'R$ 1.500,00',
        'confiabilidade' => 'Excelente qualidade',
    ],
    [
        'id_2' => 3,
        'fornecedor' => 'Cimpor',
        'especialidade' => 'base_estrutura',
        'marca_principal' => 'Cimento Branco',
        'troca_devolucao' => 'Até 15 dias',
        'prazo_entrega' => '48h',
        'nome_consultor' => 'Roberta Silva',
        'contato' => '(11) 98765-4321',
        'email' => 'pedidos@cimpor.com.br',
        'cnpj' => '03.456.789/0001-91',
        'pagamento_condicacao' => 'Boleto 35 dias',
        'pedido_min' => 'R$ 2.500,00',
        'confiabilidade' => 'Alta',
    ],
    [
        'id_2' => 4,
        'fornecedor' => 'Quartzolit',
        'especialidade' => 'base_estrutura',
        'marca_principal' => 'Argamassas',
        'troca_devolucao' => 'Até 20 dias',
        'prazo_entrega' => '48h',
        'nome_consultor' => 'Pedro Lima',
        'contato' => '(11) 97777-1111',
        'email' => 'vendas@quartzolit.com.br',
        'cnpj' => '04.567.890/0001-92',
        'pagamento_condicacao' => 'Boleto 28 dias',
        'pedido_min' => 'R$ 1.800,00',
        'confiabilidade' => 'Alta',
    ],
    [
        'id_2' => 5,
        'fornecedor' => 'CSN Cimentos',
        'especialidade' => 'base_estrutura',
        'marca_principal' => 'Cimento CP II',
        'troca_devolucao' => 'Só com nota',
        'prazo_entrega' => '72h',
        'nome_consultor' => 'João Pereira',
        'contato' => '(11) 96666-2222',
        'email' => 'csn@cimento.com.br',
        'cnpj' => '05.678.901/0001-93',
        'pagamento_condicacao' => 'Boleto 30 dias',
        'pedido_min' => 'R$ 2.000,00',
        'confiabilidade' => 'Boa',
    ],
    [
        'id_2' => 6,
        'fornecedor' => 'Holcim',
        'especialidade' => 'base_estrutura',
        'marca_principal' => 'Cimento Holcim',
        'troca_devolucao' => 'Até 20 dias',
        'prazo_entrega' => '72h',
        'nome_consultor' => 'Ana Costa',
        'contato' => '(11) 95555-1111',
        'email' => 'holcim@cimento.com',
        'cnpj' => '06.111.111/0001-01',
        'pagamento_condicacao' => 'Boleto 28 dias',
        'pedido_min' => 'R$ 2.200,00',
        'confiabilidade' => 'Alta',
    ],
    [
        'id_2' => 7,
        'fornecedor' => 'InterCement',
        'especialidade' => 'base_estrutura',
        'marca_principal' => 'Cimento Estrutural',
        'troca_devolucao' => '15 dias',
        'prazo_entrega' => '48h',
        'nome_consultor' => 'Lucas Dias',
        'contato' => '(11) 94444-2222',
        'email' => 'inter@cimento.com',
        'cnpj' => '07.222.222/0001-02',
        'pagamento_condicacao' => 'Boleto 30 dias',
        'pedido_min' => 'R$ 2.000,00',
        'confiabilidade' => 'Alta',
    ],
    [
        'id_2' => 8,
        'fornecedor' => 'Supremo Cimentos',
        'especialidade' => 'base_estrutura',
        'marca_principal' => 'Cimento CP V',
        'troca_devolucao' => '20 dias',
        'prazo_entrega' => '72h',
        'nome_consultor' => 'Fernanda Alves',
        'contato' => '(11) 93333-3333',
        'email' => 'supremo@cimento.com',
        'cnpj' => '08.333.333/0001-03',
        'pagamento_condicacao' => 'Boleto 35 dias',
        'pedido_min' => 'R$ 2.300,00',
        'confiabilidade' => 'Alta',
    ],

    // ================= HIDRÁULICA E ESGOTO (9-16) =================
    [
        'id_2' => 9,
        'fornecedor' => 'Amanco Wavin',
        'especialidade' => 'hidraulica_esgoto',
        'marca_principal' => 'Amanco',
        'troca_devolucao' => '30 dias',
        'prazo_entrega' => 'Semanal',
        'nome_consultor' => 'Cláudia Lira',
        'contato' => '(11) 97777-6666',
        'email' => 'vendas@amanco.com.br',
        'cnpj' => '12.345.678/0001-00',
        'pagamento_condicacao' => 'Boleto',
        'pedido_min' => 'R$ 1.500,00',
        'confiabilidade' => 'Excelente',
    ],
    [
        'id_2' => 10,
        'fornecedor' => 'Tigre',
        'especialidade' => 'hidraulica_esgoto',
        'marca_principal' => 'Tubos PVC',
        'troca_devolucao' => 'Garantia 36 meses',
        'prazo_entrega' => '3 dias',
        'nome_consultor' => 'Fernando Costa',
        'contato' => '(11) 96543-2109',
        'email' => 'comercial@tigre.com.br',
        'cnpj' => '13.456.789/0001-01',
        'pagamento_condicacao' => 'Crédito',
        'pedido_min' => 'R$ 1.000,00',
        'confiabilidade' => 'Excelente',
    ],
    [
        'id_2' => 11,
        'fornecedor' => 'TUPY',
        'especialidade' => 'hidraulica_esgoto',
        'marca_principal' => 'Tubulações',
        'troca_devolucao' => '60 dias',
        'prazo_entrega' => '7 dias',
        'nome_consultor' => 'Patricia Oliveira',
        'contato' => '(11) 95432-1098',
        'email' => 'pedidos@tupy.com.br',
        'cnpj' => '14.567.890/0001-02',
        'pagamento_condicacao' => 'Antecipado',
        'pedido_min' => 'R$ 2.000,00',
        'confiabilidade' => 'Alta',
    ],
    [
        'id_2' => 12,
        'fornecedor' => 'Deca',
        'especialidade' => 'hidraulica_esgoto',
        'marca_principal' => 'Louças e Metais',
        'troca_devolucao' => '30 dias',
        'prazo_entrega' => '5 dias',
        'nome_consultor' => 'Bruno Alves',
        'contato' => '(11) 98888-3333',
        'email' => 'vendas@deca.com.br',
        'cnpj' => '17.111.222/0001-05',
        'pagamento_condicacao' => 'Boleto',
        'pedido_min' => 'R$ 1.200,00',
        'confiabilidade' => 'Alta',
    ],
    [
        'id_2' => 13,
        'fornecedor' => 'Docol',
        'especialidade' => 'hidraulica_esgoto',
        'marca_principal' => 'Torneiras',
        'troca_devolucao' => '45 dias',
        'prazo_entrega' => '4 dias',
        'nome_consultor' => 'Lucas Martins',
        'contato' => '(11) 97777-4444',
        'email' => 'docol@vendas.com',
        'cnpj' => '18.222.333/0001-06',
        'pagamento_condicacao' => '30 dias',
        'pedido_min' => 'R$ 1.300,00',
        'confiabilidade' => 'Boa',
    ],
    [
        'id_2' => 14,
        'fornecedor' => 'Lorenzetti',
        'especialidade' => 'hidraulica_esgoto',
        'marca_principal' => 'Chuveiros e aquecedores',
        'troca_devolucao' => '90 dias',
        'prazo_entrega' => '5 dias',
        'nome_consultor' => 'Juliana Reis',
        'contato' => '(11) 93333-4444',
        'email' => 'lorenzetti@vendas.com',
        'cnpj' => '19.444.555/0001-07',
        'pagamento_condicacao' => 'Boleto',
        'pedido_min' => 'R$ 1.200,00',
        'confiabilidade' => 'Alta',
    ],
    [
        'id_2' => 15,
        'fornecedor' => 'Fabrimar',
        'especialidade' => 'hidraulica_esgoto',
        'marca_principal' => 'Metais sanitários',
        'troca_devolucao' => '30 dias',
        'prazo_entrega' => '6 dias',
        'nome_consultor' => 'Paulo Nunes',
        'contato' => '(11) 92222-5555',
        'email' => 'fabrimar@vendas.com',
        'cnpj' => '20.555.666/0001-08',
        'pagamento_condicacao' => '30 dias',
        'pedido_min' => 'R$ 1.100,00',
        'confiabilidade' => 'Boa',
    ],
    [
        'id_2' => 16,
        'fornecedor' => 'Blukit',
        'especialidade' => 'hidraulica_esgoto',
        'marca_principal' => 'Conexões hidráulicas',
        'troca_devolucao' => '60 dias',
        'prazo_entrega' => '5 dias',
        'nome_consultor' => 'Renata Souza',
        'contato' => '(11) 91111-6666',
        'email' => 'blukit@vendas.com',
        'cnpj' => '21.666.777/0001-09',
        'pagamento_condicacao' => 'Boleto',
        'pedido_min' => 'R$ 1.300,00',
        'confiabilidade' => 'Alta',
    ],

    // ================= REVESTIMENTOS (17-24) =================
    [
        'id_2' => 17,
        'fornecedor' => 'Pisos Porto Ferreira',
        'especialidade' => 'revestimentos',
        'marca_principal' => 'Cerâmicas',
        'troca_devolucao' => '3% quebra',
        'prazo_entrega' => '10 dias',
        'nome_consultor' => 'Elaine Pisos',
        'contato' => '(19) 92222-1111',
        'email' => 'porto@ferreira.com.br',
        'cnpj' => '67.890.123/0001-55',
        'pagamento_condicacao' => '50/50',
        'pedido_min' => '50 m²',
        'confiabilidade' => 'Alta',
    ],
    [
        'id_2' => 18,
        'fornecedor' => 'Brasital',
        'especialidade' => 'revestimentos',
        'marca_principal' => 'Azulejos',
        'troca_devolucao' => '100 dias',
        'prazo_entrega' => '8 dias',
        'nome_consultor' => 'Gustavo Rocha',
        'contato' => '(11) 94321-0987',
        'email' => 'vendas@brasital.com.br',
        'cnpj' => '15.678.901/0001-03',
        'pagamento_condicacao' => 'Boleto',
        'pedido_min' => '30 m²',
        'confiabilidade' => 'Alta',
    ],
    [
        'id_2' => 19,
        'fornecedor' => 'Portobello',
        'especialidade' => 'revestimentos',
        'marca_principal' => 'Porcelanatos',
        'troca_devolucao' => '60 dias',
        'prazo_entrega' => '6 dias',
        'nome_consultor' => 'Mariana Santos',
        'contato' => '(11) 93210-6789',
        'email' => 'vendas@portobello.com.br',
        'cnpj' => '16.789.012/0001-04',
        'pagamento_condicacao' => '50/50',
        'pedido_min' => '40 m²',
        'confiabilidade' => 'Premium',
    ],
    [
        'id_2' => 20,
        'fornecedor' => 'Eliane',
        'especialidade' => 'revestimentos',
        'marca_principal' => 'Revestimentos',
        'troca_devolucao' => '30 dias',
        'prazo_entrega' => '7 dias',
        'nome_consultor' => 'Ricardo Melo',
        'contato' => '(11) 95555-6666',
        'email' => 'eliane@vendas.com',
        'cnpj' => '19.333.444/0001-07',
        'pagamento_condicacao' => 'Boleto',
        'pedido_min' => '35 m²',
        'confiabilidade' => 'Alta',
    ],
    [
        'id_2' => 21,
        'fornecedor' => 'Incepa',
        'especialidade' => 'revestimentos',
        'marca_principal' => 'Pisos e Azulejos',
        'troca_devolucao' => '45 dias',
        'prazo_entrega' => '6 dias',
        'nome_consultor' => 'Fernanda Luz',
        'contato' => '(11) 94444-7777',
        'email' => 'incepa@vendas.com',
        'cnpj' => '20.444.555/0001-08',
        'pagamento_condicacao' => '30 dias',
        'pedido_min' => '40 m²',
        'confiabilidade' => 'Alta',
    ],
    [
        'id_2' => 22,
        'fornecedor' => 'Ceusa',
        'especialidade' => 'revestimentos',
        'marca_principal' => 'Porcelanatos premium',
        'troca_devolucao' => '60 dias',
        'prazo_entrega' => '7 dias',
        'nome_consultor' => 'Daniel Rocha',
        'contato' => '(11) 93333-7777',
        'email' => 'ceusa@vendas.com',
        'cnpj' => '22.777.888/0001-10',
        'pagamento_condicacao' => 'Boleto',
        'pedido_min' => '45 m²',
        'confiabilidade' => 'Premium',
    ],
    [
        'id_2' => 23,
        'fornecedor' => 'Roca',
        'especialidade' => 'revestimentos',
        'marca_principal' => 'Louças e revestimentos',
        'troca_devolucao' => '30 dias',
        'prazo_entrega' => '5 dias',
        'nome_consultor' => 'André Lima',
        'contato' => '(11) 92222-8888',
        'email' => 'roca@vendas.com',
        'cnpj' => '23.888.999/0001-11',
        'pagamento_condicacao' => '30 dias',
        'pedido_min' => '35 m²',
        'confiabilidade' => 'Alta',
    ],
    [
        'id_2' => 24,
        'fornecedor' => 'Biancogres',
        'especialidade' => 'revestimentos',
        'marca_principal' => 'Porcelanatos',
        'troca_devolucao' => '45 dias',
        'prazo_entrega' => '6 dias',
        'nome_consultor' => 'Camila Torres',
        'contato' => '(11) 91111-9999',
        'email' => 'biancogres@vendas.com',
        'cnpj' => '24.999.000/0001-12',
        'pagamento_condicacao' => 'Boleto',
        'pedido_min' => '40 m²',
        'confiabilidade' => 'Alta',
    ],

];

?>